name: veterinaria
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=5.5.0=pyhd8ed1ab_1
  - arrow-cpp=19.0.0=hb704434_4
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.0=h46256e1_1
  - aws-c-cal=0.9.2=h80a239a_0
  - aws-c-common=0.12.3=h6e16a3a_0
  - aws-c-compression=0.3.1=hdea44ad_5
  - aws-c-event-stream=0.5.5=h01412b5_0
  - aws-c-http=0.10.2=ha1444c5_2
  - aws-c-io=0.20.1=h46256e1_0
  - aws-c-mqtt=0.13.2=he61ece7_0
  - aws-c-s3=0.8.3=h46256e1_0
  - aws-c-sdkutils=0.2.4=hdea44ad_0
  - aws-checksums=0.2.7=hdea44ad_1
  - aws-crt-cpp=0.32.10=h6d0c2b6_0
  - aws-sdk-cpp=1.11.528=he026a02_1
  - blinker=1.9.0=pyhff2d567_0
  - boost-cpp=1.78.0=h179ae3a_0
  - brotli-python=1.0.9=py310h7a76584_9
  - bzip2=1.0.8=h6c40b1e_6
  - c-ares=1.34.5=hf13058a_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cachetools=6.2.1=pyhd8ed1ab_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - expat=2.7.1=h6d0c2b6_0
  - freetype=2.10.4=h4cff582_1
  - gflags=2.2.2=hac325c4_1005
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glog=0.5.0=h25b26a9_0
  - icu=70.1=h96cf925_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9e=hb7f2c08_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - lcms2=2.16=h31d93a5_1
  - lerc=4.0.0=hcca01a6_1
  - libabseil=20250127.0=cxx17_h548131f_0
  - libblas=3.9.0=38_he492b99_openblas
  - libbrotlicommon=1.0.9=hb7f2c08_9
  - libbrotlidec=1.0.9=hb7f2c08_9
  - libbrotlienc=1.0.9=hb7f2c08_9
  - libcblas=3.9.0=38_h9b27e0a_openblas
  - libcurl=8.14.1=h1448931_1
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.22=h00291cd_0
  - libev=4.33=h10d778d_2
  - libevent=2.1.12=ha90c15b_1
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=15.2.0=h306097a_1
  - libgfortran5=15.2.0=h336fb69_1
  - libgrpc=1.71.0=hf2926fd_0
  - liblapack=3.9.0=38_h859234e_openblas
  - libnghttp2=1.57.0=h9beae6a_0
  - libopenblas=0.3.30=openmp_h6006d49_3
  - libpng=1.6.39=h6c40b1e_0
  - libprotobuf=5.29.3=h66a43dd_1
  - libre2-11=2024.07.02=hab2016f_0
  - libssh2=1.11.1=h3a17b82_0
  - libthrift=0.15.0=h70b4b81_2
  - libtiff=4.7.0=h2dfa3ea_0
  - libwebp-base=1.6.0=hb807250_0
  - llvm-openmp=19.1.7=h5048363_2
  - lz4-c=1.9.4=hf0c8a7f_0
  - markupsafe=3.0.3=py310hd951482_0
  - narwhals=2.10.2=pyhcf101f3_0
  - ncurses=6.5=h923df54_0
  - numpy=2.2.6=py310h07c5b4d_0
  - openjpeg=2.5.2=h2d09ccc_1
  - openssl=3.5.4=h230baf5_0
  - orc=2.1.1=h4dda5a6_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h39ce848_1
  - pillow=11.1.0=py310h935ef2f_1
  - pip=25.2=pyhc872135_1
  - protobuf=5.29.3=py310h8d5cf9e_0
  - pyarrow=19.0.0=py310h6d0c2b6_1
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.18=hc958d9f_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310hd951482_0
  - re2=2024.07.02=h1962661_0
  - readline=8.3=h49f2429_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rpds-py=0.28.0=py310h64024f4_1
  - setuptools=78.1.1=py310hecd8cb5_0
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h25c286d_0
  - sqlite=3.50.2=hc8b0dd6_1
  - streamlit=1.51.0=pyhd8ed1ab_0
  - tenacity=9.1.2=pyhd8ed1ab_0
  - tk=8.6.15=h3a5a201_0
  - toml=0.10.2=pyhd8ed1ab_1
  - tornado=6.5.2=py310hd2d5e8d_2
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - utf8proc=2.6.1=h6c40b1e_1
  - watchdog=6.0.0=py310h1b7cace_1
  - wheel=0.45.1=py310hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - yaml=0.2.5=h4132b18_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
prefix: /opt/anaconda3/envs/veterinaria
